# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carpart', '0001_initial'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order date')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Date of receipt')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='Provider')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('cart_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpart.CarPart', verbose_name='Cart part')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Order')),
            ],
        ),
    ]
