# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Price'),
        ),
    ]
